abbr --add d 'docker'
abbr --add dl 'docker logs'
abbr --add dlf 'docker logs -f'
abbr --add dc 'docker compose'
abbr --add dcu 'docker compose up -d'
abbr --add dcub 'docker compose up -d --build'
abbr --add dcd 'docker compose down'
abbr --add dcl 'docker compose logs'
abbr --add dclf 'docker compose logs -f'
