abbr --add g       'git'
abbr --add ga      'git add'
abbr --add gap     'git add --patch'
abbr --add gb      'git branch'
abbr --add gba     'git branch -a'
abbr --add gco     'git checkout'
abbr --add gcp     'git cherry-pick'
abbr --add gcpa    'git cherry-pick --abort'
abbr --add gcpc    'git cherry-pick --continue'
abbr --add gc      'git commit -v'
abbr --add gca     'git commit --amend --no-edit'
abbr --add gd      'git diff'
abbr --add gds     'git diff --staged'
abbr --add gdup    'git diff @{upstream}'
abbr --add gdft    'git difftool'
abbr --add gdfts   'git difftool --staged'
abbr --add gdftup  'git difftool @{upstream}'
abbr --add gf      'git fetch'
abbr --add gfo     'git fetch origin'
abbr --add gl      'git log'
abbr --add glo     'git log --oneline --decorate'
abbr --add glg     'git log --graph --decorate'
abbr --add glog    'git log --oneline --graph --decorate'
abbr --add gloga   'git log --oneline --graph --decorate --all'
abbr --add glogaa  'git log --oneline --graph --decorate --all --format="%C(auto)%h %C(auto)%d%Creset [%C(blue)%an%Creset] %C(auto)%s%Creset"'
abbr --add gp      'git pull'
abbr --add gP      'git push'
abbr --add gPo     'git push origin'
abbr --add gPu     'git push @{upstream}'
abbr --add grb     'git rebase'
abbr --add grbi    'git rebase -i'
abbr --add grba    'git rebase --abort'
abbr --add grbc    'git rebase --continue'
abbr --add grbm    'git rebase origin/main'
abbr --add gre     'git reset'
abbr --add greh    'git reset --hard'
abbr --add grehh   'git reset --hard HEAD'
abbr --add grehh~  'git reset --hard HEAD~'
abbr --add grs     'git restore'
abbr --add grss    'git restore --staged'
abbr --add gst     'git status'
abbr --add gstap   'git stash push'
abbr --add gstapop 'git stash pop'
abbr --add gstaa   'git stash apply'
abbr --add gstad   'git stash drop'
abbr --add gstal   'git stash list'
abbr --add gstas   'git stash show --patch'
abbr --add gsw     'git switch'
abbr --add gswm    'git switch main'
abbr --add gswc    'git switch -c'
