vim.cmd("cnoreabbrev g       Git")
vim.cmd("cnoreabbrev ga      Git add")
vim.cmd("cnoreabbrev gap     Git add --patch")
vim.cmd("cnoreabbrev gb      Git branch")
vim.cmd("cnoreabbrev gba     Git branch -a")
vim.cmd("cnoreabbrev gco     Git checkout")
vim.cmd("cnoreabbrev gcp     Git cherry-pick")
vim.cmd("cnoreabbrev gcpa    Git cherry-pick --abort")
vim.cmd("cnoreabbrev gcpc    Git cherry-pick --continue")
vim.cmd("cnoreabbrev gc      tab Git commit -v")
vim.cmd("cnoreabbrev gca     Git commit --amend --no-edit")
vim.cmd("cnoreabbrev gd      Gdiffsplit")
vim.cmd("cnoreabbrev gds     Git diff --staged")
vim.cmd("cnoreabbrev gdup    Git diff @{upstream}")
vim.cmd("cnoreabbrev gdft    Git difftool")
vim.cmd("cnoreabbrev gdfts   Git difftool --staged")
vim.cmd("cnoreabbrev gdftup  Git difftool @{upstream}")
vim.cmd("cnoreabbrev gf      Git fetch")
vim.cmd("cnoreabbrev gfo     Git fetch origin")
vim.cmd("cnoreabbrev gl      Git log")
vim.cmd("cnoreabbrev glo     Git log --oneline --decorate")
vim.cmd("cnoreabbrev glg     Git log --graph --decorate")
vim.cmd("cnoreabbrev glog    Git log --oneline --graph --decorate")
vim.cmd("cnoreabbrev gloga   Git log --oneline --graph --decorate --all")
vim.cmd(
	'cnoreabbrev glogaa  Git log --oneline --graph --decorate --all --format="%C(auto)%h %C(auto)%d%Creset [%C(blue)%an%Creset] %C(auto)%s%Creset"'
)
vim.cmd("cnoreabbrev gp      Git pull")
vim.cmd("cnoreabbrev gP      Git push")
vim.cmd("cnoreabbrev gPo     Git push origin")
vim.cmd("cnoreabbrev gPu     Git push @{upstream}")
vim.cmd("cnoreabbrev grb     Git rebase")
vim.cmd("cnoreabbrev grbi    Git rebase -i")
vim.cmd("cnoreabbrev grba    Git rebase --abort")
vim.cmd("cnoreabbrev grbc    Git rebase --continue")
vim.cmd("cnoreabbrev grbm    Git rebase origin/main")
vim.cmd("cnoreabbrev gre     Git reset")
vim.cmd("cnoreabbrev greh    Git reset --hard")
vim.cmd("cnoreabbrev grehh   Git reset --hard HEAD")
vim.cmd("cnoreabbrev grehh~  Git reset --hard HEAD~")
vim.cmd("cnoreabbrev grs     Git restore")
vim.cmd("cnoreabbrev grss    Git restore --staged")
vim.cmd("cnoreabbrev gst     Git status")
vim.cmd("cnoreabbrev gstap   Git stash push")
vim.cmd("cnoreabbrev gstapop Git stash pop")
vim.cmd("cnoreabbrev gstaa   Git stash apply")
vim.cmd("cnoreabbrev gstad   Git stash drop")
vim.cmd("cnoreabbrev gstal   Git stash list")
vim.cmd("cnoreabbrev gstas   Git stash show --patch")
vim.cmd("cnoreabbrev gsw     Git switch")
vim.cmd("cnoreabbrev gswm    Git switch main")
vim.cmd("cnoreabbrev gswc    Git switch -c")
